# Generated by Django 4.1 on 2022-08-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
        ('contatos', '0004_contato_foto'),
    ]

    operations = [
    ]
